#!/usr/bin/env bash
source $(dirname $0)/../lib/page.sh

setUp() {
  export MARKDOWN=$(cat "$(dirname $0)/samples/1.md")
}

testMarkdownEnvVar() {
  assertTrue \
    "MARKDOWN is set" \
    "[[ -n \${MARKDOWN} ]]"

  assertEquals \
    "MARKDOWN has length" \
    '298' $(echo "${MARKDOWN}" | wc -c)
}

testPageHeading() {
  assertEquals \
    "The Heading" "$(_page_heading)"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
