#!/usr/bin/env bash
source $(dirname $0)/../lib/page.sh

setUp() {
  export MARKDOWN=$(cat "$(dirname $0)/samples/1.md")
}

testMarkdownEnvVar() {
  assertTrue \
    "MARKDOWN is set" \
    "[[ -n \${MARKDOWN} ]]"

  assertEquals \
    "MARKDOWN has length" \
    '298' $(echo "${MARKDOWN}" | wc -c)
}

testPageHeading() {
  assertEquals \
    "The Heading" "$(_page_heading)"
}

testPageSource() {
  assertEquals \
    "http://example.com/blah.html" "$(_page_source)"
}

testPageRefSource() {
  assertEquals \
    'http://www.google.com/' "$(_page_ref_source 1)"

  assertEquals \
    'blah2.jpg' "$(_page_ref_source 2)"

  assertEquals \
    'http://www.google.com/blah3.jpg' "$(_page_ref_source 3)"
}

testPageImageRefs() {
  assertTrue \
    "without alt tag" \
    "_page_image_refs | grep '^2$'"

  assertTrue \
    "with alt tag" \
    "_page_image_refs | grep '^3$'"

  assertTrue \
    "inline image" \
    "_page_image_refs | grep '^5$'"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
