#!/usr/bin/env bash
source $(dirname $0)/../lib/slug.sh

setUp() {
  export MARKDOWN=$(cat "$(dirname $0)/samples/1.md")
}

testSlug() {
  assertEquals \
    "the-heading" "$(_slug 'The Heading')"
}

testFileName() {
  assertTrue \
    "has md extension" \
    '[[ "$(_filename "test")" =~ \.md$ ]]'

  assertTrue \
    "has date" \
    '[[ "$(_filename "test")" =~ ^[0-9]{8}- ]]'

  assertTrue \
    "has slug" \
    '[[ "$(_filename "test")" =~ test\.md ]]'
}

testAssetDirectory() {
  assertTrue \
    "blah" \
    '[[ "$(_asset_directory "blah")" =~ ^[0-9]{8}-blah$ ]]'
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
