#!/usr/bin/env bash
source $(dirname $0)/../lib/assets.sh

setUp() {
  export MARKDOWN=$(cat "$(dirname $0)/samples/1.md")
  export DATE=$(date +%Y%m%d)
}

testImages() {
  assertTrue \
    "without alt tag" \
    "_image_refs | grep '^2$'"

  assertTrue \
    "with alt tag" \
    "_image_refs | grep '^3$'"

  assertTrue \
    "inline image" \
    "_image_refs | grep '^5$'"
}

testAssetUrl() {
  assertEquals \
    'http://www.google.com/' "$(_asset_url 1)"

  assertEquals \
    'blah2.jpg' "$(_asset_url 2)"

  assertEquals \
    'http://www.google.com/blah3.jpg' "$(_asset_url 3)"
}

test_asset_filename() {
  assertEquals \
    "an unqualified asset filename" \
    "${DATE}-the-heading/blah2.jpg" "$(_asset_filename 2)"

  assertEquals \
    "a fully qualified asset filename" \
    "${DATE}-the-heading/blah3.jpg" "$(_asset_filename 3)"
}


# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
